# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  build-and-push-docker-image:
    name: build docker image and push to repo
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: log in to Github packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: build image and push to docker hub and github container registry
        uses: docker/build-push-action@v3
        with: 
          context: ./
          tags: /
            Sumanrana834275/react-app:${{ github.sha }}
            ghcr.io/Sumanrana834275/react-app:${{ github.sha }}
          push: ${{github.ref == 'refs/heads/main'}}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.diggest}}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: suman-repo/infra
          ref: 'main'
          token: ${{ secrets.G_TOKEN}}
      - name: setup git config
        run: /
          git config --global user.email "suman.rana@cloud.cbnits.com"
          git config --global user.name "suman"
          echo ${{ github.sha }}
          sed.i "s#${{github.actor}}.*#${{ github.actor }}/suman-repo:${{ github.sha }}#g" deployment.yaml
          git add -A 
          git commit -am "Update image for - ${{ github.sha}}"
      - run: echo ${{ github }}
      - run: git push origin main

