apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: suman233/suman_react
        ports:
        - containerPort: 80





# apiversion: v1
# kind: Deployment
# metadata:
#   name: react-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#     app: react-app
#   template:
#     metadata:
#       labels:
#         app: react-app
#     spec:
#       container:
#         - name: react-app
#           image: suman233/suman_react
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 80

    