apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  labels:
        app: react-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: react-app
  type: LoadBalancer





# apiversion: v1
# kind: Service
# metadata:
#   name: react-app-service
#   labels:
#       app: react-app

# spec:
#   type: NodePort
#   selector:
#     app: react-app
#   ports:
#     - port: 80
#       protocol: TCP
#       targetPort: 80
#       nodePort: 31000
